// Data kuis
export const quizzes = [
  {
    id: 1,
    title: "Aljabar Linear Dasar",
    description: "Uji pemahaman Anda tentang konsep dasar aljabar linear",
    category: "Matematika",
    difficulty: "Menengah",
    totalQuestions: 15,
    duration: "30 menit",
    dueDate: "2023-05-20",
    status: "available",
    progress: 0,
    image: "/placeholder.svg?height=100&width=200",
    questions: [
      {
        id: 1,
        question: "Apa yang dimaksud dengan vektor?",
        options: [
          "Besaran yang hanya memiliki nilai",
          "Besaran yang memiliki nilai dan arah",
          "Besaran yang hanya memiliki arah",
          "Besaran yang tidak memiliki nilai dan arah",
        ],
        correctAnswer: 1,
        explanation: "Vektor adalah besaran yang memiliki nilai (magnitudo) dan arah.",
      },
      {
        id: 2,
        question: "Jika A dan B adalah matriks, maka A + B = B + A adalah contoh dari sifat...",
        options: ["Asosiatif", "Komutatif", "Distributif", "Identitas"],
        correctAnswer: 1,
        explanation: "Sifat komutatif menyatakan bahwa urutan operasi penjumlahan tidak mempengaruhi hasil.",
      },
      // Tambahkan pertanyaan lainnya
    ],
  },
  {
    id: 2,
    title: "Hukum Newton",
    description: "Kuis tentang hukum gerak Newton dan aplikasinya",
    category: "Fisika",
    difficulty: "Dasar",
    totalQuestions: 10,
    duration: "20 menit",
    dueDate: "2023-05-18",
    status: "available",
    progress: 0,
    image: "/placeholder.svg?height=100&width=200",
  },
  {
    id: 3,
    title: "Tabel Periodik Unsur",
    description: "Menguji pengetahuan Anda tentang tabel periodik dan sifat unsur",
    category: "Kimia",
    difficulty: "Dasar",
    totalQuestions: 20,
    duration: "40 menit",
    dueDate: "2023-05-25",
    status: "available",
    progress: 0,
    image: "/placeholder.svg?height=100&width=200",
  },
  {
    id: 4,
    title: "Grammar Bahasa Inggris",
    description: "Kuis tentang tata bahasa Inggris dasar",
    category: "Bahasa Inggris",
    difficulty: "Dasar",
    totalQuestions: 25,
    duration: "45 menit",
    dueDate: "2023-05-15",
    status: "in_progress",
    progress: 40,
    image: "/placeholder.svg?height=100&width=200",
  },
  {
    id: 5,
    title: "Kalkulus Diferensial",
    description: "Uji pemahaman Anda tentang konsep turunan dan aplikasinya",
    category: "Matematika",
    difficulty: "Lanjut",
    totalQuestions: 15,
    duration: "45 menit",
    dueDate: "2023-05-22",
    status: "in_progress",
    progress: 60,
    image: "/placeholder.svg?height=100&width=200",
  },
  {
    id: 6,
    title: "Termodinamika",
    description: "Kuis tentang prinsip-prinsip termodinamika",
    category: "Fisika",
    difficulty: "Menengah",
    totalQuestions: 12,
    duration: "30 menit",
    dueDate: "2023-05-10",
    status: "completed",
    score: 85,
    image: "/placeholder.svg?height=100&width=200",
  },
  {
    id: 7,
    title: "Reaksi Kimia Organik",
    description: "Menguji pengetahuan Anda tentang reaksi kimia organik",
    category: "Kimia",
    difficulty: "Lanjut",
    totalQuestions: 20,
    duration: "50 menit",
    dueDate: "2023-05-05",
    status: "completed",
    score: 92,
    image: "/placeholder.svg?height=100&width=200",
  },
  {
    id: 8,
    title: "Public Speaking",
    description: "Kuis tentang teknik dan strategi public speaking",
    category: "Bahasa Inggris",
    difficulty: "Menengah",
    totalQuestions: 15,
    duration: "30 menit",
    dueDate: "2023-05-08",
    status: "completed",
    score: 78,
    image: "/placeholder.svg?height=100&width=200",
  },
  {
    id: 9,
    title: "Ujian Tengah Semester Matematika",
    description: "Ujian komprehensif tentang materi matematika semester ini",
    category: "Matematika",
    difficulty: "Menengah",
    totalQuestions: 30,
    duration: "120 menit",
    date: "20 Mei 2023",
    time: "09:00 - 11:00",
    status: "upcoming",
    image: "/placeholder.svg?height=100&width=200",
  },
  {
    id: 10,
    title: "Ujian Praktikum Fisika",
    description: "Ujian praktikum tentang konsep fisika dasar",
    category: "Fisika",
    difficulty: "Menengah",
    totalQuestions: 15,
    duration: "90 menit",
    date: "22 Mei 2023",
    time: "13:00 - 15:00",
    status: "upcoming",
    image: "/placeholder.svg?height=100&width=200",
  },
]
